name: ping automation-tick endpoint

on:
  schedule:
    - cron: "0 * * * *"   # toutes les heures à HH:00 UTC
  workflow_dispatch: {}

jobs:
  call:
    runs-on: ubuntu-latest
    env:
      BASE_URL: https://planning-mmg.ovh
      CRON_KEY: ${{ secrets.CRON_SECRET }}
    steps:
      - name: Vérifier la présence du secret
        run: |
          if [ -z "$CRON_KEY" ]; then
            echo "::error::CRON_SECRET manquant dans les secrets du dépôt"; exit 1; fi
      - name: Appeler /automation-tick (dry-run, verbeux)
        run: |
          set -euo pipefail
          URL="$BASE_URL/api/admin/automation-tick?dry-run=1&key=$CRON_KEY"
          echo "→ $URL"
          curl -fsS -L --max-time 25 --retry 3 --retry-connrefused \
               -w "\nHTTP %{http_code}\n" \
               "$URL"
