name: Cron

on:
  schedule:
    - cron: '0 6 * * *'   # existant pour /api/admin/cron
    - cron: '0 * * * *'   # NOUVEAU: tick emails toutes les heures
  workflow_dispatch:

jobs:
  daily-periods:
    runs-on: ubuntu-latest
    steps:
      - name: Tick daily periods
        run: |
          curl -fsSL "${{ secrets.PUBLIC_URL }}/api/admin/cron?token=${{ secrets.CRON_TOKEN }}"

  hourly-automation:
    runs-on: ubuntu-latest
    steps:
      - name: Tick email automation
        run: |
          curl -fsSL "${{ secrets.PUBLIC_URL }}/api/admin/automation-tick?token=${{ secrets.CRON_TOKEN }}"
